"use client";

import { useEffect, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";
import { AuthUser, getUser, isAdmin } from "@/lib/auth";
type UserRow={id:number;username:string;role_id:number;role:"ADMIN"|"OPERATOR"};
export default function UsersPage(){
  const [me,setMe]=useState<AuthUser|null>(null);const [users,setUsers]=useState<UserRow[]>([]);const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [role,setRole]=useState<"ADMIN"|"OPERATOR">("OPERATOR");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=async()=>{const current=getUser();setMe(current);if(!isAdmin(current))return;try{setUsers(await fetchApi("/auth/users"));}catch(e){setError(e instanceof Error?e.message:"Could not load users")}};useEffect(()=>{load()},[]);
  async function addUser(e:React.FormEvent){e.preventDefault();setError("");setMessage("");try{await fetchApi("/auth/users",{method:"POST",body:JSON.stringify({username:username.trim(),password,role})});setUsername("");setPassword("");setRole("OPERATOR");setMessage("User added.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not add user")}}
  async function changeRole(user:UserRow,next:"ADMIN"|"OPERATOR"){try{await fetchApi(`/auth/users/${user.id}/role`,{method:"PATCH",body:JSON.stringify({role:next})});await load();}catch(e){setError(e instanceof Error?e.message:"Could not change role")}}
  async function resetPassword(user:UserRow){const password=window.prompt(`New password for ${user.username}:`);if(!password)return;try{await fetchApi(`/auth/users/${user.id}/password`,{method:"PATCH",body:JSON.stringify({password})});setMessage("Password updated.");}catch(e){setError(e instanceof Error?e.message:"Could not reset password")}}
  async function removeUser(user:UserRow){if(!window.confirm(`Delete ${user.username}?`))return;try{await fetchApi(`/auth/users/${user.id}`,{method:"DELETE"});await load();}catch(e){setError(e instanceof Error?e.message:"Could not delete user")}}
  if(me&&!isAdmin(me))return <div className="dsr-page"><Header title="Users"/><main className="dsr-main"><div className="rounded-lg border border-red-900 bg-red-950/20 p-4 text-red-300">Admin access required.</div></main></div>;
  return <div className="dsr-page"><Header title="Users"/><main className="dsr-main"><div className="full-bleed space-y-4"><div className="dsr-section-head"><div><div className="dsr-kicker">Access control</div><h1 className="dsr-title">Users</h1><p className="dsr-subtitle">Viewer access is public. Operators edit plant data. Admins also manage users and master data.</p></div></div>{error&&<div className="rounded-lg border border-red-900 bg-red-950/25 p-3 text-sm text-red-300">{error}</div>}{message&&<div className="rounded-lg border border-emerald-900 bg-emerald-950/20 p-3 text-sm text-emerald-300">{message}</div>}
  <form onSubmit={addUser} className="mechanical-panel p-4 grid grid-cols-1 md:grid-cols-4 gap-3"><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" required className="input-class"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Temporary password" required className="input-class"/><select value={role} onChange={e=>setRole(e.target.value as any)} className="input-class"><option value="OPERATOR">Operator</option><option value="ADMIN">Admin</option></select><button className="dsr-btn-primary">Add User</button></form>
  <div className="dsr-table-wrap"><table className="dsr-table min-w-[680px]"><thead><tr><th className="dsr-th">Username</th><th className="dsr-th">Role</th><th className="dsr-th">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td className="dsr-td font-bold text-white">{u.username}</td><td className="dsr-td"><select value={u.role} onChange={e=>changeRole(u,e.target.value as any)} className="input-class !w-auto !py-1"><option>OPERATOR</option><option>ADMIN</option></select></td><td className="dsr-td"><div className="flex gap-2"><button onClick={()=>resetPassword(u)} className="dsr-btn !min-h-0 !py-1">Reset Password</button><button onClick={()=>removeUser(u)} className="dsr-btn !min-h-0 !py-1 text-red-300">Delete</button></div></td></tr>)}</tbody></table></div>
  </div></main></div>;
}
