"use client";

import { useEffect, useMemo, useState } from "react";
import { fetchApi } from "@/lib/api";
import { getUser } from "@/lib/auth";

type ComponentRow={component_type_id:number;name:string;required_qty:number|null;new_qty:number;reused_qty:number;carried_life_hours:number|null;expected_life_hours:number|null;criticality:string|null;is_extra:boolean};
export default function ComponentPreparationModal({stand,onClose,onComplete}:{stand:any;onClose:()=>void;onComplete:()=>Promise<void>|void}){
  const [rows,setRows]=useState<ComponentRow[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notes,setNotes]=useState("");const user=getUser();
  useEffect(()=>{(async()=>{try{const d=await fetchApi(`/stands/${stand.id}/components`);setRows(d.components||[]);setNotes(d.notes||"");}catch(e:any){setError(e.message);}finally{setLoading(false);}})();},[stand.id]);
  const filled=useMemo(()=>rows.filter(r=>(r.new_qty||0)+(r.reused_qty||0)>0).length,[rows]);const complete=useMemo(()=>rows.filter(r=>r.required_qty!==null).every(r=>(r.new_qty||0)+(r.reused_qty||0)===r.required_qty),[rows]);
  function change(id:number,key:"new_qty"|"reused_qty"|"carried_life_hours",value:string){const n=value===""?null:Math.max(0,Number(value)||0);setRows(v=>v.map(r=>r.component_type_id===id?{...r,[key]:n}:r));}
  async function save(skip:boolean){setSaving(true);setError("");try{await fetchApi(`/stands/${stand.id}/components`,{method:"POST",body:JSON.stringify({prepared_by:user?.username||"Operator",notes,skip,items:skip?[]:rows.map(r=>({component_type_id:r.component_type_id,new_qty:r.new_qty||0,reused_qty:r.reused_qty||0,carried_life_hours:(r.reused_qty||0)>0?r.carried_life_hours:null}))})});await fetchApi("/operations/stands/status",{method:"POST",body:JSON.stringify({stand_code:stand.code,status:"GAUGING",updated_by:user?.username||"Operator",remarks:skip?"Components skipped before gauging":"Components saved before gauging"})});await onComplete();onClose();}catch(e:any){setError(e.message||"Could not save components");}finally{setSaving(false);}}
  return <div className="fixed inset-0 z-[60] bg-black/70 flex items-end md:items-center justify-center md:p-4" onClick={onClose}><div className="w-full max-w-5xl max-h-[92vh] overflow-auto rounded-t-2xl md:rounded-xl border border-[#34445a] bg-[#0f1725]" onClick={e=>e.stopPropagation()}>
    <div className="border-b border-[#26354a] bg-blue-950/15 p-4 md:p-5 flex items-start justify-between gap-3"><div><div className="dsr-kicker">Before Gauging</div><h2 className="text-xl font-bold text-white mt-1">Stand {stand.code} · Components</h2><p className="mt-1 text-sm text-slate-400">Enter New and Reused quantities. Previous life is optional when known.</p></div><button onClick={onClose} className="dsr-btn">Close</button></div>
    <div className="p-4 md:p-5">{error&&<div className="mb-3 rounded-lg border border-red-900 bg-red-950/25 p-3 text-sm text-red-300">{error}</div>}{loading?<div className="dsr-empty">Loading component list...</div>:<><div className="dsr-table-wrap"><table className="dsr-table min-w-[760px]"><thead><tr><th className="dsr-th">Component</th><th className="dsr-th text-center">Required</th><th className="dsr-th text-center">New</th><th className="dsr-th text-center">Reused</th><th className="dsr-th text-center">Previous life (h)</th><th className="dsr-th text-center">Check</th></tr></thead><tbody>{rows.map(r=>{const total=(r.new_qty||0)+(r.reused_qty||0);const ok=r.required_qty==null?total>0:total===r.required_qty;return <tr key={r.component_type_id}><td className="dsr-td font-semibold text-white">{r.name}{r.is_extra&&<span className="ml-2 rounded-full bg-blue-950/60 px-2 py-1 text-[9px] font-bold text-blue-300">ENTRY GUIDE EXTRA</span>}</td><td className="dsr-td text-center font-semibold">{r.required_qty??"As fitted"}</td><td className="dsr-td text-center"><input type="number" min="0" value={r.new_qty||0} onChange={e=>change(r.component_type_id,"new_qty",e.target.value)} className="input-class !w-20 !py-1.5 text-center"/></td><td className="dsr-td text-center"><input type="number" min="0" value={r.reused_qty||0} onChange={e=>change(r.component_type_id,"reused_qty",e.target.value)} className="input-class !w-20 !py-1.5 text-center"/></td><td className="dsr-td text-center"><input type="number" min="0" disabled={(r.reused_qty||0)===0} value={r.carried_life_hours??""} onChange={e=>change(r.component_type_id,"carried_life_hours",e.target.value)} placeholder={(r.reused_qty||0)>0?"optional":"—"} className="input-class !w-28 !py-1.5 text-center disabled:opacity-35"/></td><td className="dsr-td text-center">{ok?<span className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-emerald-950/60 font-bold text-emerald-300">✓</span>:<span className="text-slate-600">—</span>}</td></tr>})}</tbody></table></div>
      <div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><div><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Component note (optional)" className="input-class"/><div className={`mt-2 text-xs ${complete?"text-emerald-300":"text-slate-400"}`}>{filled} component types recorded · {complete?"Required quantities complete":"Partial data is allowed"}</div></div><div className="flex flex-col sm:flex-row gap-2"><button disabled={saving} onClick={()=>save(true)} className="dsr-btn disabled:opacity-40">Skip → Gauging</button><button disabled={saving} onClick={()=>save(false)} className="dsr-btn-primary disabled:opacity-40">Save → Gauging</button></div></div></>}</div>
  </div></div>;
}
