"use client";
import Link from "next/link";
import { useState } from "react";
import { fetchApi } from "@/lib/api";

type VItem={index:number;state:"SAFE"|"REVIEW"|"CONFLICT";message:string;action:any};

export default function ImportReportPage() {
  const [text,setText]=useState(""); const [result,setResult]=useState<any>(null); const [validation,setValidation]=useState<any>(null); const [selected,setSelected]=useState<number[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [confirming,setConfirming]=useState(false); const [done,setDone]=useState<any>(null); const [openReview,setOpenReview]=useState<number|null>(null); const [dismissed,setDismissed]=useState<number[]>([]);
  async function analyse(){ setLoading(true);setError("");setResult(null);setValidation(null);setDone(null);setOpenReview(null);setDismissed([]); try{const r=await fetchApi("/import-report/analyse",{method:"POST",body:JSON.stringify({text})});setResult(r);const v=await fetchApi("/import-report/validate",{method:"POST",body:JSON.stringify({actions:r.actions})});setValidation(v);setSelected(v.items.filter((x:VItem)=>x.state==="SAFE").map((x:VItem)=>x.index));}catch(e:any){setError(e.message);}finally{setLoading(false);} }
  async function confirm(){ if(!result||!validation)return; const actions=validation.items.filter((x:VItem)=>selected.includes(x.index)&&x.state==="SAFE").map((x:VItem)=>x.action); if(!actions.length)return; if(!window.confirm(`Apply ${actions.length} safe update(s) to Digital Stand Register?`))return; setConfirming(true);setError(""); try{const r=await fetchApi("/import-report/confirm",{method:"POST",body:JSON.stringify({actions})});setDone(r);const v=await fetchApi("/import-report/validate",{method:"POST",body:JSON.stringify({actions:result.actions})});setValidation(v);setSelected([]);}catch(e:any){setError(e.message);}finally{setConfirming(false);} }
  const badge=(s:string)=>s==="SAFE"?"bg-emerald-950 text-emerald-300 border-emerald-800":s==="REVIEW"?"bg-amber-950 text-amber-300 border-amber-800":"bg-red-950 text-red-300 border-red-800";
  return <main className="p-4 md:p-5 max-w-7xl mx-auto space-y-4">
    <div><h1 className="text-xl font-bold text-white">Import Report</h1><p className="text-xs text-slate-400">Paste shift / WhatsApp report → Analyse → Check → Confirm.</p></div>
    <textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste stand report here..." className="w-full h-52 rounded-xl bg-slate-950 border border-slate-700 p-4 text-sm text-slate-100 outline-none focus:border-blue-500" />
    <button disabled={!text.trim()||loading} onClick={analyse} className="px-5 py-2 rounded-lg bg-blue-600 disabled:opacity-40 text-white text-sm font-semibold">{loading?"Analysing...":"Analyse Report"}</button>
    {error&&<div className="rounded-lg border border-red-900 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}
    {result&&validation&&<section className="space-y-3">
      <div className="flex flex-wrap gap-2 text-xs"><span className="px-2 py-1 rounded bg-slate-800 text-slate-200">{result.provider==="gemini"?"Gemini AI":"Template parser"}</span><span className="px-2 py-1 rounded bg-emerald-950 text-emerald-300">{validation.counts.SAFE} Safe</span><span className="px-2 py-1 rounded bg-amber-950 text-amber-300">{validation.counts.REVIEW} Review</span><span className="px-2 py-1 rounded bg-red-950 text-red-300">{validation.counts.CONFLICT} Conflict</span></div>
      <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-2 w-16">Action</th><th className="p-2 text-left">Check</th><th className="p-2 text-left">Type</th><th className="p-2 text-left">Stand</th><th className="p-2 text-left">Line / Position</th><th className="p-2 text-left">What DSR found</th></tr></thead><tbody>{validation.items.map((x:VItem)=><>
        <tr key={`row-${x.index}`} className={`border-t border-slate-800 text-slate-200 ${dismissed.includes(x.index)?"opacity-40":""}`}><td className="p-2">{x.state==="SAFE"?<input type="checkbox" checked={selected.includes(x.index)} onChange={e=>setSelected(e.target.checked?[...selected,x.index]:selected.filter(i=>i!==x.index))}/>:x.state==="REVIEW"?<button onClick={()=>setOpenReview(openReview===x.index?null:x.index)} className="px-2 py-1 rounded border border-amber-700 text-amber-300 hover:bg-amber-950/50">{openReview===x.index?"Close":"Resolve"}</button>:<span className="text-red-400">Blocked</span>}</td><td className="p-2"><span className={`px-2 py-1 rounded border ${badge(x.state)}`}>{x.state}</span></td><td className="p-2 font-semibold">{x.action.type}</td><td className="p-2">{x.action.stand||`${x.action.stand_removed||"?"} → ${x.action.stand_fixed||"?"}`}</td><td className="p-2">{x.action.line?`${x.action.line}${x.action.position?` / ${x.action.position}`:""}`:"—"}</td><td className="p-2 max-w-md">{x.message}</td></tr>
        {openReview===x.index&&x.state==="REVIEW"&&<tr key={`review-${x.index}`} className="border-t border-slate-800 bg-amber-950/10"><td colSpan={6} className="p-3"><div className="flex flex-wrap items-center gap-3"><div className="text-amber-200 font-semibold">Review required</div><div className="text-slate-300">{x.message}</div>{x.action.type?.startsWith("ENTRY_GUIDE")&&<Link href="/entry-guides" className="px-3 py-1.5 rounded bg-blue-600 text-white hover:bg-blue-500">Open Entry Guides</Link>}<button onClick={()=>{setDismissed(dismissed.includes(x.index)?dismissed.filter(i=>i!==x.index):[...dismissed,x.index]);setOpenReview(null);}} className="px-3 py-1.5 rounded border border-slate-700 text-slate-300 hover:bg-slate-800">{dismissed.includes(x.index)?"Restore":"Ignore this item"}</button></div><div className="mt-2 text-[11px] text-slate-500">Review items are never written automatically. Resolve them manually, then re-analyse the report if needed.</div></td></tr>}
      </>)}</tbody></table></div>
      {result.warnings?.map((w:string,i:number)=><div key={i} className="text-xs text-amber-300">⚠ {w}</div>)}
      <div className="flex items-center gap-3"><button disabled={!selected.length||confirming} onClick={confirm} className="px-5 py-2 rounded-lg bg-emerald-600 disabled:opacity-40 text-white text-sm font-semibold">{confirming?"Updating...":`Confirm ${selected.length} Safe Update${selected.length===1?"":"s"}`}</button><span className="text-xs text-slate-500">Safe items can be applied. Review items now have a Resolve button.</span></div>
      {done&&<div className="rounded-lg border border-emerald-900 bg-emerald-950/25 p-3 text-sm text-emerald-300">Updated {done.updated} item(s). Stand Area and History now use the new data.</div>}
    </section>}
  </main>;
}
