"use client";

import { useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Row={date:string;activity:string;stand:string;done_by:string;details:string};type StageEvent={date:string;done_by:string;details:string};type StandSummary={stand:string;gauging?:StageEvent;hydrotest?:StageEvent;ready?:StageEvent;latest:number};
function fmtDate(v:string){return new Date(v).toLocaleString([], {day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}
function StageCell({event}:{event?:StageEvent}){if(!event)return <span className="text-slate-700">—</span>;return <div><div className="font-bold text-slate-100">{event.done_by||"—"}</div><div className="mt-1 text-[9px] text-slate-500">{fmtDate(event.date)}</div></div>}
export default function ActivityPage(){
 const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [tab,setTab]=useState<"readiness"|"changes">("readiness");
 useEffect(()=>{fetchApi("/activity/").then(setRows).catch(e=>setError(e instanceof Error?e.message:"Failed to load history")).finally(()=>setLoading(false));},[]);
 const readiness=useMemo(()=>{const map=new Map<string,StandSummary>();for(const row of rows){if(!["Gauging","Hydrotest","Ready"].includes(row.activity))continue;const stamp=new Date(row.date).getTime();const item=map.get(row.stand)||{stand:row.stand,latest:stamp};item.latest=Math.max(item.latest,stamp);const event={date:row.date,done_by:row.done_by,details:row.details};if(row.activity==="Gauging"&&!item.gauging)item.gauging=event;if(row.activity==="Hydrotest"&&!item.hydrotest)item.hydrotest=event;if(row.activity==="Ready"&&!item.ready)item.ready=event;map.set(row.stand,item);}return Array.from(map.values()).sort((a,b)=>b.latest-a.latest);},[rows]);
 const changes=useMemo(()=>rows.filter(r=>r.activity==="Stand Change"),[rows]);
 return <div className="dsr-page"><Header title="History"/><main className="dsr-main"><div className="full-bleed space-y-3"><div className="dsr-section-head"><div><div className="dsr-kicker">Traceability</div><h1 className="dsr-title">Stand History</h1><p className="dsr-subtitle">One clean record for readiness; stand changes stay separate.</p></div><div className="grid grid-cols-2 gap-1 rounded-lg border border-slate-800 bg-[#0a0f15] p-1"><button onClick={()=>setTab("readiness")} className={tab==="readiness"?"dsr-btn-primary !min-h-0":"dsr-btn !min-h-0"}>Readiness</button><button onClick={()=>setTab("changes")} className={tab==="changes"?"dsr-btn-primary !min-h-0":"dsr-btn !min-h-0"}>Stand Changes</button></div></div>
 {error&&<div className="rounded-lg border border-red-900 bg-red-950/25 p-3 text-xs text-red-300">{error}</div>}
 {tab==="readiness"?<section className="mechanical-panel overflow-hidden"><div className="px-4 py-3 border-b border-slate-800 flex items-center justify-between"><div><div className="dsr-kicker">Preparation completion</div><div className="text-sm font-black text-white">Readiness History</div></div><span className="dsr-chip">{readiness.length} stands</span></div><div className="dsr-table-wrap !rounded-none !border-0"><table className="dsr-table min-w-[760px]"><thead><tr><th className="dsr-th">Stand</th><th className="dsr-th">Gauging</th><th className="dsr-th">Hydrotest</th><th className="dsr-th">Ready</th><th className="dsr-th">Latest Note</th></tr></thead><tbody>{readiness.map(row=>{const remarks=row.ready?.details||row.hydrotest?.details||row.gauging?.details||"";return <tr key={row.stand} className="hover:bg-slate-900/50"><td className="dsr-td text-base font-black text-white">{row.stand}</td><td className="dsr-td"><StageCell event={row.gauging}/></td><td className="dsr-td"><StageCell event={row.hydrotest}/></td><td className="dsr-td"><StageCell event={row.ready}/></td><td className="dsr-td">{remarks||"—"}</td></tr>})}{!loading&&readiness.length===0&&<tr><td colSpan={5} className="dsr-empty">No readiness history yet.</td></tr>}{loading&&<tr><td colSpan={5} className="dsr-empty">Loading history...</td></tr>}</tbody></table></div></section>:<section className="mechanical-panel overflow-hidden"><div className="px-4 py-3 border-b border-slate-800 flex items-center justify-between"><div><div className="dsr-kicker">Line changeovers</div><div className="text-sm font-black text-white">Stand Changes</div></div><span className="dsr-chip">{changes.length} records</span></div><div className="dsr-table-wrap !rounded-none !border-0"><table className="dsr-table min-w-[720px]"><thead><tr><th className="dsr-th">Date & Time</th><th className="dsr-th">Stand Change</th><th className="dsr-th">Done By</th><th className="dsr-th">Reason / Note</th></tr></thead><tbody>{changes.map((row,i)=><tr key={`${row.date}-${i}`} className="hover:bg-slate-900/50"><td className="dsr-td whitespace-nowrap">{new Date(row.date).toLocaleString()}</td><td className="dsr-td font-black text-white">{row.stand}</td><td className="dsr-td">{row.done_by||"—"}</td><td className="dsr-td">{row.details||"—"}</td></tr>)}{!loading&&changes.length===0&&<tr><td colSpan={4} className="dsr-empty">No stand changes recorded yet.</td></tr>}</tbody></table></div></section>}
 </div></main></div>
}
