"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

const fmt=(v:any,s="")=>v===null||v===undefined?"—":`${v}${s}`;
const label=(v:string)=>(v||"").replaceAll("_"," ");

export default function InvestigationPage(){
  const params=useSearchParams();
  const [line,setLine]=useState(params.get("line")||"W1");
  const [position,setPosition]=useState(Number(params.get("position")||8));
  const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{setData(await fetchApi(`/investigation/position?line=${line}&position=${position}`));}catch(e:any){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load()},[]);
  return <div className="flex-1 min-h-screen bg-industrial-dark text-slate-100"><Header title="Stand Life Investigation"/><main className="p-4 md:p-5 max-w-7xl space-y-4">
    <section className="rounded-xl border border-slate-800 bg-slate-900/45 p-4"><div className="flex flex-wrap items-end gap-3"><div><div className="text-[10px] text-slate-500 uppercase">Line</div><select value={line} onChange={e=>setLine(e.target.value)} className="mt-1 bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm">{["W1","W2","W3"].map(x=><option key={x}>{x}</option>)}</select></div><div><div className="text-[10px] text-slate-500 uppercase">Position</div><select value={position} onChange={e=>setPosition(Number(e.target.value))} className="mt-1 bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm">{Array.from({length:10},(_,i)=>i+1).map(x=><option key={x} value={x}>P{x}</option>)}</select></div><button onClick={load} disabled={loading} className="bg-blue-600 rounded px-4 py-2 text-sm font-semibold disabled:opacity-50">{loading?"Analysing...":"Investigate"}</button><div className="text-xs text-slate-500">Historical sources stay separate; this screen only aligns them by date.</div></div></section>
    {error&&<div className="rounded-lg border border-red-900 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}
    {data&&<>
      <section className="grid grid-cols-2 md:grid-cols-6 gap-3">{[["Campaigns",data.campaigns],["Avg life",fmt(data.avg_days," d")],["Median",fmt(data.median_days," d")],["Shortest",fmt(data.min_days," d")],["Longest",fmt(data.max_days," d")],["Early",data.early_campaigns??0]].map(([k,v])=><div key={String(k)} className="rounded-lg border border-slate-800 bg-slate-900/40 p-3"><div className="text-[10px] text-slate-500 uppercase">{k}</div><div className="text-xl font-black mt-1">{v}</div></div>)}</section>
      {data.message&&<div className="text-sm text-slate-400">{data.message}</div>}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
        <section className="rounded-xl border border-slate-800 bg-slate-900/45 overflow-hidden"><div className="p-3 border-b border-slate-800"><h2 className="font-bold">Removal causes</h2><p className="text-[11px] text-slate-500">Normalized only from historical remarks.</p></div><div className="p-3 space-y-2">{data.causes?.length?data.causes.map((x:any,i:number)=><div key={i} className="flex justify-between text-xs border-b border-slate-800 pb-2"><span>{label(x.cause)}</span><b>{x.count}</b></div>):<div className="text-xs text-slate-500">No coded remarks yet.</div>}</div></section>
        <section className="rounded-xl border border-slate-800 bg-slate-900/45 overflow-hidden"><div className="p-3 border-b border-slate-800"><h2 className="font-bold">Stand-code performance</h2><p className="text-[11px] text-slate-500">Useful for spotting a physical stand that repeatedly underperforms at this position.</p></div><table className="w-full text-xs"><thead className="text-slate-500"><tr><th className="p-2 text-left">Stand</th><th>Runs</th><th>Avg</th><th>Median</th><th>Early</th></tr></thead><tbody>{data.stand_codes?.map((x:any,i:number)=><tr key={i} className="border-t border-slate-800"><td className="p-2 font-bold">{x.stand}</td><td className="text-center">{x.campaigns}</td><td className="text-center">{fmt(x.avg_days," d")}</td><td className="text-center">{fmt(x.median_days," d")}</td><td className="text-center">{x.early_campaigns}</td></tr>)}</tbody></table></section>
      </div>
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
        <section className="rounded-xl border border-slate-800 bg-slate-900/45 overflow-hidden"><div className="p-3 border-b border-slate-800"><h2 className="font-bold">Spare use near early campaigns</h2><p className="text-[11px] text-slate-500">Independent spare history within ±2 days of early campaign windows. This is screening, not proof the spare caused the change.</p></div><table className="w-full text-xs"><thead className="text-slate-500"><tr><th className="p-2 text-left">Spare</th><th className="p-2 text-right">Qty</th></tr></thead><tbody>{data.nearby_spares?.map((x:any,i:number)=><tr key={i} className="border-t border-slate-800"><td className="p-2">{x.spare}</td><td className="p-2 text-right font-bold">{x.quantity}</td></tr>)}</tbody></table>{!data.nearby_spares?.length&&<div className="p-3 text-xs text-slate-500">No overlapping spare-usage records yet.</div>}</section>
        <section className="rounded-xl border border-slate-800 bg-slate-900/45 overflow-hidden"><div className="p-3 border-b border-slate-800"><h2 className="font-bold">Process comparison</h2><p className="text-[11px] text-slate-500">WRM process records during early campaigns versus all imported observations for this line.</p></div><table className="w-full text-xs"><thead className="text-slate-500"><tr><th className="p-2 text-left">Parameter</th><th>All avg</th><th>Early avg</th><th>Diff</th><th>Early N</th></tr></thead><tbody>{data.process?.map((x:any,i:number)=><tr key={i} className="border-t border-slate-800"><td className="p-2">{x.parameter}</td><td className="text-center">{fmt(x.overall_avg)}</td><td className="text-center">{fmt(x.early_avg)}</td><td className="text-center font-bold">{fmt(x.difference_pct,"%")}</td><td className="text-center">{x.early_samples}</td></tr>)}</tbody></table>{!data.process?.length&&<div className="p-3 text-xs text-slate-500">No process observations imported for this line yet.</div>}</section>
      </div>
      <section className="rounded-xl border border-slate-800 bg-slate-900/45 overflow-hidden"><div className="p-3 border-b border-slate-800"><h2 className="font-bold">Campaign timeline</h2><p className="text-[11px] text-slate-500">Red rows are ≤60% of this position's historical median.</p></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="text-slate-500"><tr><th className="p-2 text-left">Stand</th><th>Installed</th><th>Removed</th><th>Life</th><th className="text-left">Cause / remark</th><th>Source</th></tr></thead><tbody>{data.timeline?.map((x:any,i:number)=><tr key={i} className={`border-t border-slate-800 ${x.early?"bg-red-950/15":""}`}><td className="p-2 font-bold">{x.stand}</td><td className="text-center">{x.installed}</td><td className="text-center">{x.removed}</td><td className={`text-center font-bold ${x.early?"text-red-300":""}`}>{fmt(x.life_days," d")}</td><td className="p-2"><div>{label(x.cause)}</div><div className="text-[10px] text-slate-500">{x.reason||"No remark"}</div></td><td className="text-center text-[10px] text-slate-500">Historical / inferred</td></tr>)}</tbody></table></div></section>
      <div className="rounded-lg border border-amber-900/50 bg-amber-950/15 p-3 text-[11px] text-amber-200">{data.method_note}</div>
    </>}
  </main></div>;
}
