"use client";

import { useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Stand={id:number;code:string;current_status:string};type PositionRow={id:number;lineName:string;positionNumber:number;currentStand:string};
const REASONS=["Roll wear / size deviation","Bearing issue","Leakage","Vibration","Abnormal sound","Scheduled rotation","Breakdown","Other"];
const CONDITIONS=["Normal","Leakage","Vibration","Abnormal Sound","Leakage + Vibration","Other"];
export default function OperationsPage(){
  const [stands,setStands]=useState<Stand[]>([]);const [positions,setPositions]=useState<PositionRow[]>([]);const [positionId,setPositionId]=useState("");const [replacement,setReplacement]=useState("");const [changedBy,setChangedBy]=useState("");const [reason,setReason]=useState("");const [condition,setCondition]=useState("Normal");const [notes,setNotes]=useState("");const [timeMode,setTimeMode]=useState<"now"|"custom">("now");const [customTime,setCustomTime]=useState("");const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  const load=async()=>{try{setError("");const [lineData,standData]=await Promise.all([fetchApi("/dashboard/"),fetchApi("/stands/")]);const mapped:PositionRow[]=[];lineData.forEach((line:any)=>line.positions?.forEach((pos:any)=>{if(pos.current_stand)mapped.push({id:pos.id,lineName:line.name,positionNumber:pos.position_number,currentStand:pos.current_stand.code});}));setPositions(mapped);setStands(standData);if(!positionId&&mapped.length)setPositionId(String(mapped[0].id));}catch(err){setError(err instanceof Error?err.message:"Could not load stand data");}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const selectedPosition=useMemo(()=>positions.find(p=>p.id===Number(positionId)),[positions,positionId]);const readyStands=stands.filter(s=>s.current_status==="READY");
  const submitChange=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedPosition||!replacement||!changedBy.trim()||!reason){setError("Select position, replacement stand, name and reason.");return;}if(timeMode==="custom"&&!customTime){setError("Select the stand change date and time.");return;}setSubmitting(true);setError("");setMessage("");try{const changedAt=timeMode==="custom"?new Date(customTime).toISOString():null;const leakage=condition.includes("Leakage");const vibration=condition.includes("Vibration");const abnormalSound=condition==="Abnormal Sound";await fetchApi("/operations/stands/change",{method:"POST",body:JSON.stringify({position_id:selectedPosition.id,removed_stand_code:selectedPosition.currentStand,installed_stand_code:replacement,changed_by:changedBy.trim(),reason,changed_at:changedAt,notes:notes.trim()||null,removed_condition:condition,leakage,vibration,abnormal_sound:abnormalSound})});setMessage(`${selectedPosition.currentStand} → ${replacement} saved. Removed stand moved to Pending.`);setReplacement("");setChangedBy("");setReason("");setNotes("");setCondition("Normal");setTimeMode("now");setCustomTime("");await load();}catch(err){setError(err instanceof Error?err.message:"Stand change failed");}finally{setSubmitting(false)}};
  return <div className="dsr-page"><Header title="Stand Change"/><main className="dsr-main"><div className="full-bleed grid gap-3 lg:grid-cols-[minmax(0,1fr)_340px]">
    <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="dsr-kicker">Line operation</div><h1 className="dsr-title">Record Stand Change</h1><p className="dsr-subtitle">Designed for quick tablet entry on the shop floor.</p></div></div>
      <div className="p-4 md:p-5">{error&&<div className="mb-3 rounded-lg border border-red-900 bg-red-950/25 p-3 text-xs text-red-300">{error}</div>}{message&&<div className="mb-3 rounded-lg border border-emerald-900 bg-emerald-950/25 p-3 text-xs text-emerald-300">{message}</div>}{loading?<div className="dsr-empty">Loading line status...</div>:<form onSubmit={submitChange} className="space-y-5">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Running position"><select value={positionId} onChange={e=>setPositionId(e.target.value)} className="input-class min-h-[44px]">{positions.map(p=><option key={p.id} value={p.id}>{p.lineName} · P{p.positionNumber} · {p.currentStand}</option>)}</select></Field><Field label="Ready replacement"><select value={replacement} onChange={e=>setReplacement(e.target.value)} required className="input-class min-h-[44px]"><option value="">Select Ready stand</option>{readyStands.map(s=><option key={s.id} value={s.code}>{s.code}</option>)}</select></Field><Field label="Changed by"><input value={changedBy} onChange={e=>setChangedBy(e.target.value)} required placeholder="Operator / technician" className="input-class min-h-[44px]"/></Field><Field label="Change time"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setTimeMode("now")} className={`${timeMode==="now"?"dsr-btn-primary":"dsr-btn"} min-h-[44px]`}>Now</button><button type="button" onClick={()=>setTimeMode("custom")} className={`${timeMode==="custom"?"dsr-btn-primary":"dsr-btn"} min-h-[44px]`}>Custom</button></div>{timeMode==="custom"&&<input type="datetime-local" value={customTime} onChange={e=>setCustomTime(e.target.value)} className="input-class mt-2" required/>}</Field></div>
        <ChipGroup label="Reason" items={REASONS} value={reason} onChange={setReason}/>
        <ChipGroup label="Removed stand condition" items={CONDITIONS} value={condition} onChange={setCondition}/>
        <Field label="Observation (optional)"><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Short note only if needed" className="input-class min-h-[44px]"/></Field>
        <div className="flex flex-col-reverse gap-2 border-t border-slate-800 pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="text-[11px] text-slate-400">Removed stand automatically returns to Pending.</div><button disabled={submitting} type="submit" className="dsr-btn-primary min-h-[46px] min-w-[180px]">{submitting?"Saving...":"Confirm Stand Change"}</button></div>
      </form>}</div>
    </section>
    <aside className="space-y-3"><div className="mechanical-panel p-4"><div className="flex items-center justify-between"><div className="dsr-kicker">Change preview</div><button form="" disabled={submitting||!selectedPosition||!replacement||!changedBy.trim()||!reason} onClick={(e)=>{e.preventDefault();document.querySelector<HTMLFormElement>('form')?.requestSubmit()}} className="hidden lg:inline-flex dsr-btn-primary">Confirm</button></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><div className="rounded-lg border border-slate-800 bg-[#090e14] p-3 text-center"><div className="metric-label">Remove</div><div className="mt-1 text-xl font-black text-white">{selectedPosition?.currentStand||"—"}</div><div className="mt-1 text-[10px] text-slate-400">{selectedPosition?`${selectedPosition.lineName} · P${selectedPosition.positionNumber}`:"Select position"}</div></div><div className="text-cyan-400 font-black">→</div><div className="rounded-lg border border-cyan-900/60 bg-cyan-950/10 p-3 text-center"><div className="metric-label">Install</div><div className="mt-1 text-xl font-black text-cyan-200">{replacement||"—"}</div><div className="mt-1 text-[10px] text-slate-400">Ready stand</div></div></div>{reason&&<div className="mt-3 rounded-lg border border-slate-800 bg-slate-950/40 p-3 text-xs text-slate-300"><b>Reason:</b> {reason}<br/><b>Condition:</b> {condition}</div>}</div><div className="mechanical-panel p-4"><div className="dsr-kicker">Ready coverage</div><div className="mt-2 text-3xl font-black text-white">{readyStands.length}</div><div className="text-[10px] text-slate-400">Ready stands available across positions</div></div></aside>
  </div></main></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="metric-label">{label}</span><div className="mt-1.5">{children}</div></label>}
function ChipGroup({label,items,value,onChange}:{label:string;items:string[];value:string;onChange:(v:string)=>void}){return <div><div className="metric-label mb-2">{label}</div><div className="flex flex-wrap gap-2">{items.map(x=><button key={x} type="button" onClick={()=>onChange(x)} className={`min-h-[44px] rounded-lg border px-3 py-2 text-sm font-medium ${value===x?"border-blue-500 bg-blue-500/15 text-blue-200":"border-slate-700 bg-slate-950/40 text-slate-300 hover:border-slate-500"}`}>{x}</button>)}</div></div>}
