"use client";

import { useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Stand={id:number;code:string;current_status:string};type PositionRow={id:number;lineName:string;positionNumber:number;currentStand:string};
export default function OperationsPage(){
  const [stands,setStands]=useState<Stand[]>([]);const [positions,setPositions]=useState<PositionRow[]>([]);const [positionId,setPositionId]=useState("");const [replacement,setReplacement]=useState("");const [changedBy,setChangedBy]=useState("");const [reason,setReason]=useState("");const [condition,setCondition]=useState("Normal");const [notes,setNotes]=useState("");const [timeMode,setTimeMode]=useState<"now"|"custom">("now");const [customTime,setCustomTime]=useState("");const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  const load=async()=>{try{setError("");const [lineData,standData]=await Promise.all([fetchApi("/dashboard/"),fetchApi("/stands/")]);const mapped:PositionRow[]=[];lineData.forEach((line:any)=>line.positions?.forEach((pos:any)=>{if(pos.current_stand)mapped.push({id:pos.id,lineName:line.name,positionNumber:pos.position_number,currentStand:pos.current_stand.code});}));setPositions(mapped);setStands(standData);if(!positionId&&mapped.length)setPositionId(String(mapped[0].id));}catch(err){setError(err instanceof Error?err.message:"Could not load stand data");}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const selectedPosition=useMemo(()=>positions.find(p=>p.id===Number(positionId)),[positions,positionId]);const readyStands=stands.filter(s=>s.current_status==="READY");
  const submitChange=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedPosition||!replacement||!changedBy.trim()||!reason){setError("Select position, replacement stand, name and reason.");return;}if(timeMode==="custom"&&!customTime){setError("Select the stand change date and time.");return;}setSubmitting(true);setError("");setMessage("");try{const changedAt=timeMode==="custom"?new Date(customTime).toISOString():null;await fetchApi("/operations/stands/change",{method:"POST",body:JSON.stringify({position_id:selectedPosition.id,removed_stand_code:selectedPosition.currentStand,installed_stand_code:replacement,changed_by:changedBy.trim(),reason,changed_at:changedAt,notes:notes.trim()||null,removed_condition:condition,leakage:condition==="Leakage"||condition==="Leakage + Vibration",vibration:condition==="Vibration"||condition==="Leakage + Vibration"})});setMessage(`${selectedPosition.currentStand} → ${replacement} saved. Removed stand moved to Pending.`);setReplacement("");setChangedBy("");setReason("");setNotes("");setTimeMode("now");setCustomTime("");await load();}catch(err){setError(err instanceof Error?err.message:"Stand change failed");}finally{setSubmitting(false)}};
  return <div className="dsr-page"><Header title="Stand Change"/><main className="dsr-main"><div className="full-bleed grid gap-3 lg:grid-cols-[minmax(0,1fr)_310px]">
    <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="dsr-kicker">Line operation</div><h1 className="dsr-title">Record Stand Change</h1><p className="dsr-subtitle">Select the running position and its Ready replacement.</p></div></div>
      <div className="p-4 md:p-5">{error&&<div className="mb-3 rounded-lg border border-red-900 bg-red-950/25 p-3 text-xs text-red-300">{error}</div>}{message&&<div className="mb-3 rounded-lg border border-emerald-900 bg-emerald-950/25 p-3 text-xs text-emerald-300">{message}</div>}{loading?<div className="dsr-empty">Loading line status...</div>:<form onSubmit={submitChange} className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Running position"><select value={positionId} onChange={e=>setPositionId(e.target.value)} className="input-class">{positions.map(p=><option key={p.id} value={p.id}>{p.lineName} · P{p.positionNumber} · {p.currentStand}</option>)}</select></Field><Field label="Ready replacement"><select value={replacement} onChange={e=>setReplacement(e.target.value)} required className="input-class"><option value="">Select Ready stand</option>{readyStands.map(s=><option key={s.id} value={s.code}>{s.code}</option>)}</select></Field><Field label="Changed by"><input value={changedBy} onChange={e=>setChangedBy(e.target.value)} required placeholder="Operator / technician" className="input-class"/></Field><Field label="Reason"><select value={reason} onChange={e=>setReason(e.target.value)} required className="input-class"><option value="">Select reason</option><option>Roll wear / size deviation</option><option>Bearing issue</option><option>Leakage</option><option>Vibration</option><option>Scheduled rotation</option><option>Breakdown</option><option>Other</option></select></Field><Field label="Removed stand condition"><select value={condition} onChange={e=>setCondition(e.target.value)} className="input-class"><option>Normal</option><option>Leakage</option><option>Vibration</option><option>Leakage + Vibration</option><option>Other</option></select></Field><Field label="Change time"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setTimeMode("now")} className={timeMode==="now"?"dsr-btn-primary":"dsr-btn"}>Now</button><button type="button" onClick={()=>setTimeMode("custom")} className={timeMode==="custom"?"dsr-btn-primary":"dsr-btn"}>Custom</button></div>{timeMode==="custom"&&<input type="datetime-local" value={customTime} onChange={e=>setCustomTime(e.target.value)} className="input-class mt-2" required/>}</Field><div className="md:col-span-2"><Field label="Observation (optional)"><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Short note only if needed" className="input-class"/></Field></div><div className="md:col-span-2 flex flex-col-reverse gap-2 border-t border-slate-800 pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="text-[11px] text-slate-500">Removed stand automatically returns to Pending.</div><button disabled={submitting} type="submit" className="dsr-btn-primary min-w-[160px]">{submitting?"Saving...":"Confirm Stand Change"}</button></div></form>}</div>
    </section>
    <aside className="space-y-3"><div className="mechanical-panel p-4"><div className="dsr-kicker">Change preview</div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><div className="rounded-lg border border-slate-800 bg-[#090e14] p-3 text-center"><div className="metric-label">Remove</div><div className="mt-1 text-xl font-black text-white">{selectedPosition?.currentStand||"—"}</div><div className="mt-1 text-[10px] text-slate-500">{selectedPosition?`${selectedPosition.lineName} · P${selectedPosition.positionNumber}`:"Select position"}</div></div><div className="text-cyan-400 font-black">→</div><div className="rounded-lg border border-cyan-900/60 bg-cyan-950/10 p-3 text-center"><div className="metric-label">Install</div><div className="mt-1 text-xl font-black text-cyan-200">{replacement||"—"}</div><div className="mt-1 text-[10px] text-slate-500">Ready stand</div></div></div></div><div className="mechanical-panel p-4"><div className="dsr-kicker">Ready coverage</div><div className="mt-2 text-3xl font-black text-white">{readyStands.length}</div><div className="text-[10px] text-slate-500">Ready stands available across positions</div></div></aside>
  </div></main></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="metric-label">{label}</span><div className="mt-1.5">{children}</div></label>}
