"use client";
import {useEffect,useMemo,useState} from "react";
import Header from "@/components/layout/Header";
import {fetchApi} from "@/lib/api";
import {getUser} from "@/lib/auth";
type Row={id:number;planned_date:string;line_name?:string;equipment:string;activity:string;frequency?:string;assigned_to?:string;status:string;completed_date?:string;remarks?:string};
const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({planned_date:today(),line_name:"W1",equipment:"",activity:"",frequency:"Monthly",assigned_to:"",status:"PLANNED",completed_date:"",remarks:""});
export default function PMSchedule(){
 const [user]=useState(()=>getUser()),[rows,setRows]=useState<Row[]>([]),[month,setMonth]=useState(today().slice(0,7)),[line,setLine]=useState("ALL"),[edit,setEdit]=useState<number|null>(null),[form,setForm]=useState<any>(blank()),[error,setError]=useState("");
 const range=useMemo(()=>{const a=month.split("-").map(Number),last=new Date(a[0],a[1],0).getDate();return{start:month+"-01",end:month+"-"+String(last).padStart(2,"0")}},[month]);
 async function load(){try{setError("");let q="?start="+range.start+"&end="+range.end;if(line!=="ALL")q+="&line="+line;setRows(await fetchApi("/pm/"+q))}catch(e:any){setError(e.message||"Could not load PM schedule")}}
 useEffect(()=>{load()},[month,line]);
 function open(r?:Row){if(r){setEdit(r.id);setForm({...r,completed_date:r.completed_date||"",remarks:r.remarks||"",assigned_to:r.assigned_to||"",frequency:r.frequency||"",line_name:r.line_name||""})}else{setEdit(0);setForm({...blank(),planned_date:range.start,line_name:line==="ALL"?"W1":line})}}
 async function save(e:any){e.preventDefault();try{await fetchApi(edit?"/pm/"+edit:"/pm/",{method:edit?"PUT":"POST",body:JSON.stringify({...form,completed_date:form.completed_date||null,line_name:form.line_name||null})});setEdit(null);await load()}catch(e:any){setError(e.message||"Could not save PM activity")}}
 const grouped=useMemo(()=>rows.reduce((a:any,r)=>{(a[r.planned_date]??=[]).push(r);return a},{}),[rows]);
 return <div className="dsr-page"><Header title="PM Schedule"/><main className="dsr-main"><div className="full-bleed space-y-3">
  <div className="dsr-section-head"><div><div className="dsr-kicker">Preventive maintenance</div><h1 className="dsr-title">PM Schedule</h1><p className="dsr-subtitle">Date-wise PM plan. Add, edit and close maintenance activities.</p></div>{user&&<button className="dsr-btn-primary" onClick={()=>open()}>+ Add PM</button>}</div>
  <div className="mechanical-panel p-3 flex flex-wrap gap-2"><input type="month" className="input-class max-w-[180px]" value={month} onChange={e=>setMonth(e.target.value)}/>{["ALL","W1","W2","W3"].map(x=><button key={x} onClick={()=>setLine(x)} className={line===x?"dsr-btn-primary":"dsr-btn"}>{x}</button>)}</div>
  {error&&<div className="rounded-lg border border-red-900 p-3 text-red-300">{error}</div>}
  {Object.keys(grouped).length?Object.entries(grouped).map(([d,items]:any)=><section key={d} className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div className="font-bold text-white">{new Date(d+"T00:00:00").toLocaleDateString("en-GB",{weekday:"short",day:"2-digit",month:"short"})}</div><span className="dsr-chip">{items.length} activities</span></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-slate-400 border-b border-slate-800"><th className="p-3">Line</th><th className="p-3">Equipment</th><th className="p-3">PM activity</th><th className="p-3">Frequency</th><th className="p-3">Assigned</th><th className="p-3">Status</th><th className="p-3"></th></tr></thead><tbody>{items.map((r:Row)=><tr key={r.id} className="border-b border-slate-800/60"><td className="p-3 font-bold text-cyan-300">{r.line_name||"—"}</td><td className="p-3 text-white">{r.equipment}</td><td className="p-3 text-slate-200">{r.activity}</td><td className="p-3 text-slate-300">{r.frequency||"—"}</td><td className="p-3 text-slate-300">{r.assigned_to||"—"}</td><td className="p-3"><span className={"rounded px-2 py-1 font-bold "+(r.status==="COMPLETED"?"bg-emerald-500/15 text-emerald-300":r.status==="DEFERRED"?"bg-rose-500/15 text-rose-300":"bg-amber-500/15 text-amber-300")}>{r.status}</span></td><td className="p-3">{user&&<button className="dsr-btn" onClick={()=>open(r)}>Edit</button>}</td></tr>)}</tbody></table></div></section>):<div className="dsr-empty">No PM activities for this month.</div>}
  {edit!==null&&<div className="fixed inset-0 z-[80] bg-black/70 flex items-end md:items-center justify-center md:p-4" onClick={()=>setEdit(null)}><form onSubmit={save} onClick={e=>e.stopPropagation()} className="mechanical-panel w-full md:max-w-2xl p-4 grid grid-cols-1 md:grid-cols-2 gap-3"><div className="md:col-span-2 flex justify-between"><h2 className="font-black text-white">{edit?"Edit PM activity":"Add PM activity"}</h2><button type="button" onClick={()=>setEdit(null)} className="dsr-btn">Close</button></div><F n="Planned date"><input type="date" required className="input-class" value={form.planned_date} onChange={e=>setForm({...form,planned_date:e.target.value})}/></F><F n="Line"><select className="input-class" value={form.line_name} onChange={e=>setForm({...form,line_name:e.target.value})}><option value="">General</option><option>W1</option><option>W2</option><option>W3</option></select></F><F n="Equipment"><input required className="input-class" value={form.equipment} onChange={e=>setForm({...form,equipment:e.target.value})}/></F><F n="Frequency"><input className="input-class" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}/></F><div className="md:col-span-2"><F n="PM activity"><input required className="input-class" value={form.activity} onChange={e=>setForm({...form,activity:e.target.value})}/></F></div><F n="Assigned to"><input className="input-class" value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}/></F><F n="Status"><select className="input-class" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>PLANNED</option><option>DUE</option><option>COMPLETED</option><option>DEFERRED</option></select></F><div className="md:col-span-2"><F n="Remarks"><input className="input-class" value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></F></div><div className="md:col-span-2 flex justify-end"><button className="dsr-btn-primary">Save PM activity</button></div></form></div>}
 </div></main></div>
}
function F({n,children}:{n:string;children:any}){return <label><span className="metric-label">{n}</span><div className="mt-1">{children}</div></label>}
