"use client";
import {useEffect,useMemo,useState} from "react";
import Header from "@/components/layout/Header";import {fetchApi} from "@/lib/api";import {getUser} from "@/lib/auth";
const today=()=>new Date().toISOString().slice(0,10);
type Row={id:number;planned_date:string;line_name?:string;shift?:string;position_number?:number;stand_code?:string;equipment:string;component?:string;activity_type?:string;activity:string;from_value?:string;to_value?:string;assigned_to?:string;remarks?:string};
export default function PMActivities(){
 const[user]=useState(()=>getUser()),[rows,setRows]=useState<Row[]>([]),[month,setMonth]=useState(today().slice(0,7)),[line,setLine]=useState("ALL"),[msg,setMsg]=useState(""),[preview,setPreview]=useState<any[]>([]),[provider,setProvider]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const range=useMemo(()=>{const [y,m]=month.split("-").map(Number);return{start:month+"-01",end:month+"-"+String(new Date(y,m,0).getDate()).padStart(2,"0")}},[month]);
 async function load(){try{let q="?start="+range.start+"&end="+range.end;if(line!=="ALL")q+="&line="+line;setRows(await fetchApi("/pm/"+q))}catch(e:any){setError(e.message||"Could not load activities")}}
 useEffect(()=>{load()},[month,line]);
 async function analyse(){if(!msg.trim())return;setBusy(true);setError("");try{const r=await fetchApi("/pm/analyse-message",{method:"POST",body:JSON.stringify({text:msg})});setPreview(r.activities||[]);setProvider(r.provider||"")}catch(e:any){setError(e.message||"Analysis failed")}finally{setBusy(false)}}
 function patch(i:number,k:string,v:any){setPreview(p=>p.map((x,n)=>n===i?{...x,activity:{...x.activity,[k]:v}}:x))}
 async function confirm(){setBusy(true);try{const activities=preview.map(x=>x.activity);await fetchApi("/pm/confirm-message",{method:"POST",body:JSON.stringify({activities,source_text:msg})});setPreview([]);setMsg("");await load()}catch(e:any){setError(e.message||"Could not save activities")}finally{setBusy(false)}}
 return <div className="dsr-page"><Header title="PM Activities"/><main className="dsr-main"><div className="full-bleed space-y-4">
 <div className="dsr-section-head"><div><div className="dsr-kicker">Maintenance record</div><h1 className="dsr-title">PM Activities</h1><p className="dsr-subtitle">Paste the shift/PM message. AI separates each maintenance job into a reviewable activity table before anything is stored.</p></div></div>
 {user&&<section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Import maintenance message</div><div className="helper-text">Stand changes, couplers, pivots, entry guides, bearings, seals, inspections and other work.</div></div></div><div className="p-3"><textarea className="input-class min-h-[110px]" value={msg} onChange={e=>setMsg(e.target.value)} placeholder={"21/09/2026 B shift W1\nStand 8 changed 8.1 to 8C due leakage\nP6 coupler changed\nP4 pivot changed\nEntry guide 10 replaced"}/><div className="mt-3 flex items-center gap-2"><button className="dsr-btn-primary" disabled={busy||!msg.trim()} onClick={analyse}>{busy?"Analysing…":"Analyse message"}</button>{provider&&<span className="dsr-chip">{provider}</span>}<span className="helper-text">Preview only until Confirm.</span></div></div></section>}
 {preview.length>0&&<section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Review extracted activities</div><div className="helper-text">Correct any field before saving. AI does not write directly to plant data.</div></div><button onClick={confirm} disabled={busy} className="dsr-btn-primary">Confirm & store {preview.length}</button></div><div className="dsr-table-wrap border-0 rounded-none"><table className="dsr-table"><thead><tr><th className="dsr-th">State</th><th className="dsr-th">Date</th><th className="dsr-th">Shift</th><th className="dsr-th">Line</th><th className="dsr-th">Pos</th><th className="dsr-th">Equipment</th><th className="dsr-th">Activity</th><th className="dsr-th">From</th><th className="dsr-th">To</th><th className="dsr-th">Remarks</th></tr></thead><tbody>{preview.map((x,i)=><tr key={i}><td className="dsr-td"><span className={x.state==="READY"?"status-ok":"status-warn"}>{x.state}</span></td>{["planned_date","shift","line_name","position_number","equipment","activity","from_value","to_value","remarks"].map(k=><td key={k} className="dsr-td"><input className="table-input" value={x.activity[k]??""} onChange={e=>patch(i,k,k==="position_number"?(e.target.value?Number(e.target.value):null):e.target.value)}/></td>)}</tr>)}</tbody></table></div></section>}
 {error&&<div className="rounded-md border border-red-900 bg-red-950/20 p-3 text-red-300">{error}</div>}
 <div className="flex flex-wrap items-center gap-2"><input type="month" className="input-class max-w-[170px]" value={month} onChange={e=>setMonth(e.target.value)}/>{["ALL","W1","W2","W3"].map(x=><button key={x} onClick={()=>setLine(x)} className={line===x?"dsr-btn-primary":"dsr-btn"}>{x}</button>)}</div>
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Maintenance history</div><div className="helper-text">{rows.length} activities · newest first</div></div></div><div className="dsr-table-wrap border-0 rounded-none"><table className="dsr-table"><thead><tr><th className="dsr-th">Date</th><th className="dsr-th">Shift</th><th className="dsr-th">Line</th><th className="dsr-th">Pos</th><th className="dsr-th">Stand</th><th className="dsr-th">Equipment</th><th className="dsr-th">Activity</th><th className="dsr-th">From → To</th><th className="dsr-th">By</th><th className="dsr-th">Remarks</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="dsr-td whitespace-nowrap">{r.planned_date}</td><td className="dsr-td">{r.shift||"—"}</td><td className="dsr-td">{r.line_name||"—"}</td><td className="dsr-td">{r.position_number||"—"}</td><td className="dsr-td font-semibold text-white">{r.stand_code||"—"}</td><td className="dsr-td">{r.equipment}</td><td className="dsr-td">{r.activity}</td><td className="dsr-td whitespace-nowrap">{r.from_value||"—"} → {r.to_value||"—"}</td><td className="dsr-td">{r.assigned_to||"—"}</td><td className="dsr-td">{r.remarks||"—"}</td></tr>)}{!rows.length&&<tr><td colSpan={10} className="dsr-empty">No maintenance activities for this month.</td></tr>}</tbody></table></div></section>
 </div></main></div>
}