"use client";

import { useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Guide={id:number;code:string;condition:string;current_status:string;current_position_id:number|null;lifetime_hours:number;condition_notes?:string|null};
type Pos={id:number;label:string};

export default function EntryGuidesPage(){
  const [guides,setGuides]=useState<Guide[]>([]); const [positions,setPositions]=useState<Pos[]>([]);
  const [code,setCode]=useState(""); const [condition,setCondition]=useState("OLD"); const [notes,setNotes]=useState("");
  const [installGuide,setInstallGuide]=useState(""); const [installPos,setInstallPos]=useState("");
  const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
  const load=async()=>{try{setError("");const [g,l]=await Promise.all([fetchApi("/entry-guides/"),fetchApi("/dashboard/")]);setGuides(g);const p:Pos[]=[];l.forEach((line:any)=>line.positions?.forEach((x:any)=>{if([2,4,6,8,10].includes(x.position_number))p.push({id:x.id,label:`${line.name} · P${x.position_number}`})}));setPositions(p);}catch(e){setError(e instanceof Error?e.message:"Could not load entry guides");}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const ready=useMemo(()=>guides.filter(g=>g.current_status==="READY"),[guides]); const installed=useMemo(()=>guides.filter(g=>g.current_status==="INSTALLED"),[guides]);
  const add=async(e:React.FormEvent)=>{e.preventDefault();try{setError("");await fetchApi("/entry-guides/",{method:"POST",body:JSON.stringify({code:code.trim(),condition,notes:notes.trim()||null})});setCode("");setNotes("");setMessage("Entry guide added as Ready.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not add guide")}};
  const install=async(e:React.FormEvent)=>{e.preventDefault();const who=window.prompt("Installed by / operator name")?.trim();if(!who)return;try{await fetchApi("/entry-guides/install",{method:"POST",body:JSON.stringify({guide_code:installGuide,position_id:Number(installPos),operator_name:who})});setMessage(`${installGuide} installed.`);setInstallGuide("");setInstallPos("");await load();}catch(e){setError(e instanceof Error?e.message:"Install failed")}};
  const remove=async(g:Guide)=>{const who=window.prompt(`Who removed ${g.code}?`)?.trim();if(!who)return;const reason=window.prompt("Why was it removed?")?.trim();if(!reason)return;try{await fetchApi("/entry-guides/remove",{method:"POST",body:JSON.stringify({guide_code:g.code,removed_by:who,removal_reason:reason})});setMessage(`${g.code} removed to Pending.`);await load();}catch(e){setError(e instanceof Error?e.message:"Remove failed")}};
  const markReady=async(g:Guide)=>{const who=window.prompt(`Who made ${g.code} ready?`)?.trim();if(!who)return;try{await fetchApi("/entry-guides/ready",{method:"POST",body:JSON.stringify({guide_code:g.code,updated_by:who})});setMessage(`${g.code} is Ready.`);await load();}catch(e){setError(e instanceof Error?e.message:"Update failed")}};

  return <div className="dsr-page"><Header title="Entry Guides"/><main className="dsr-main"><div className="full-bleed space-y-3">
    <div className="dsr-section-head"><div><div className="dsr-kicker">Even positions only</div><h1 className="dsr-title">Entry Guide Register</h1><p className="dsr-subtitle">Used at positions 2, 4, 6, 8 and 10. Keep availability and installed life easy to see.</p></div><div className="flex gap-2"><span className="dsr-chip text-cyan-300">{installed.length} running</span><span className="dsr-chip text-emerald-300">{ready.length} ready</span><span className="dsr-chip">{guides.length} total</span></div></div>
    {(error||message)&&<div className={`rounded-lg border p-3 text-xs ${error?"border-red-900 bg-red-950/25 text-red-300":"border-emerald-900 bg-emerald-950/20 text-emerald-300"}`}>{error||message}</div>}
    <div className="grid gap-3 xl:grid-cols-2">
      <form onSubmit={add} className="mechanical-panel p-4"><div className="dsr-kicker">Add guide</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Guide ID"><input className="input-class" value={code} onChange={e=>setCode(e.target.value)} placeholder="EG-4-01" required/></Field><Field label="Condition"><select className="input-class" value={condition} onChange={e=>setCondition(e.target.value)}><option value="NEW">New</option><option value="OLD">Old</option></select></Field><div className="sm:col-span-2"><Field label="Note"><input className="input-class" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional"/></Field></div></div><div className="mt-3 flex justify-end"><button className="dsr-btn-primary">Add as Ready</button></div></form>
      <form onSubmit={install} className="mechanical-panel p-4"><div className="dsr-kicker text-emerald-300">Install guide</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Ready guide"><select className="input-class" value={installGuide} onChange={e=>setInstallGuide(e.target.value)} required><option value="">Select</option>{ready.map(g=><option key={g.id} value={g.code}>{g.code}</option>)}</select></Field><Field label="Install at"><select className="input-class" value={installPos} onChange={e=>setInstallPos(e.target.value)} required><option value="">Select position</option>{positions.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></Field></div><div className="mt-3 flex justify-end"><button className="dsr-btn-primary !bg-emerald-600 !border-emerald-500 hover:!bg-emerald-500">Install</button></div></form>
    </div>
    {loading?<div className="dsr-empty">Loading entry guides...</div>:<div className="dsr-table-wrap"><table className="dsr-table min-w-[760px]"><thead><tr><th className="dsr-th">Guide</th><th className="dsr-th text-center">New / Old</th><th className="dsr-th text-center">Status</th><th className="dsr-th text-center">Position</th><th className="dsr-th text-center">Life</th><th className="dsr-th">Note</th><th className="dsr-th text-center">Action</th></tr></thead><tbody>{guides.map(g=><tr key={g.id}><td className="dsr-td font-bold text-white">{g.code}</td><td className="dsr-td text-center">{g.condition}</td><td className="dsr-td text-center"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${g.current_status==="INSTALLED"?"bg-cyan-950/60 text-cyan-300":g.current_status==="READY"?"bg-emerald-950/60 text-emerald-300":"bg-amber-950/60 text-amber-300"}`}>{g.current_status}</span></td><td className="dsr-td text-center">{g.current_position_id??"—"}</td><td className="dsr-td text-center">{Number(g.lifetime_hours||0).toFixed(1)} h</td><td className="dsr-td">{g.condition_notes||"—"}</td><td className="dsr-td text-center">{g.current_status==="INSTALLED"?<button onClick={()=>remove(g)} className="dsr-btn !min-h-0 !py-1 text-amber-300">Remove</button>:g.current_status!=="READY"?<button onClick={()=>markReady(g)} className="dsr-btn !min-h-0 !py-1 text-emerald-300">Mark Ready</button>:<span className="text-slate-500">Ready</span>}</td></tr>)}</tbody></table></div>}
  </div></main></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="metric-label">{label}</span><div className="mt-1.5">{children}</div></label>}
