"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ShieldCheck } from "lucide-react";
import { API_BASE_URL } from "@/lib/api";
import { setSession } from "@/lib/auth";

export default function LoginPage(){
  const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const router=useRouter();
  async function submit(path:"login"|"bootstrap-admin"){if(!username.trim()||!password){setError("Enter username and password.");return;}setBusy(true);setError("");try{const response=await fetch(`${API_BASE_URL}/auth/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:username.trim(),password,role:"ADMIN"})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||"Sign in failed");setSession(data.access_token,data.user);router.push("/dashboard");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Sign in failed");}finally{setBusy(false)}}
  return <div className="flex-1 min-h-screen flex items-center justify-center p-5 bg-[radial-gradient(circle_at_top,rgba(59,130,246,.14),transparent_35%)]"><div className="mechanical-panel w-full max-w-md overflow-hidden"><div className="h-1 bg-gradient-to-r from-blue-500 via-cyan-400 to-violet-500"/><div className="p-6 md:p-7"><div className="flex flex-col items-center text-center mb-6"><div className="mb-3 grid h-12 w-12 place-items-center rounded-xl border border-blue-800/60 bg-blue-950/30"><ShieldCheck className="w-6 h-6 text-blue-300"/></div><h1 className="text-xl font-bold text-white">Sign In to Edit</h1><p className="mt-1 text-sm text-slate-400">Viewing stays public. Operators and admins sign in to make changes.</p></div>{error&&<div className="mb-4 rounded-lg border border-red-900 bg-red-950/25 p-3 text-sm text-red-300">{error}</div>}<div className="space-y-4"><label className="block"><span className="metric-label">Username</span><input value={username} onChange={e=>setUsername(e.target.value)} className="input-class mt-1.5" autoComplete="username"/></label><label className="block"><span className="metric-label">Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="input-class mt-1.5" autoComplete="current-password"/></label><button disabled={busy} onClick={()=>submit("login")} className="dsr-btn-primary w-full disabled:opacity-50">{busy?"Please wait...":"Sign In"}</button><div className="pt-3 border-t border-[#26354a]"><p className="helper-text mb-2">First setup only — available only while no user accounts exist.</p><button disabled={busy} onClick={()=>submit("bootstrap-admin")} className="dsr-btn w-full disabled:opacity-50">Create First Admin</button></div></div></div></div></div>;
}
