"use client";

import { useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Item={id:number;name:string;quantity:number;minimum_quantity:number;location:string;is_active:boolean;expected_life_hours?:number|null;observed_avg_life_hours?:number|null;reliability_pct?:number|null;availability_pct?:number|null;criticality?:string|null;used_at?:string|null};
type FormState={name:string;used_at:string;quantity:string;minimum_quantity:string;expected_life_hours:string;observed_avg_life_hours:string};
const blank:FormState={name:"",used_at:"",quantity:"0",minimum_quantity:"0",expected_life_hours:"",observed_avg_life_hours:""};
const n=(v:string)=>Math.max(0,Number(v)||0);const optional=(v:string)=>v.trim()===""?null:Math.max(0,Number(v));const life=(h?:number|null)=>h==null?"—":h>=24?`${(h/24).toFixed(1)} d`:`${h.toFixed(0)} h`;const pct=(v?:number|null)=>v==null?"—":`${v.toFixed(0)}%`;const rank:Record<string,number>={CRITICAL:0,HIGH:1,MEDIUM:2,LOW:3,UNASSESSED:4};
const badge=(v?:string|null)=>v==="CRITICAL"?"border-red-800/70 bg-red-950/35 text-red-300":v==="HIGH"?"border-orange-800/70 bg-orange-950/30 text-orange-300":v==="MEDIUM"?"border-amber-800/70 bg-amber-950/20 text-amber-300":v==="LOW"?"border-emerald-800/70 bg-emerald-950/20 text-emerald-300":"border-slate-700 bg-slate-900 text-slate-400";
export default function InventoryPage(){
  const [items,setItems]=useState<Item[]>([]);const [form,setForm]=useState<FormState>(blank);const [editing,setEditing]=useState<Item|null>(null);const [showForm,setShowForm]=useState(false);const [error,setError]=useState("");const [query,setQuery]=useState("");const [sort,setSort]=useState<"AZ"|"CRITICAL"|"LOW_STOCK">("AZ");const [saving,setSaving]=useState(false);
  const load=async()=>{try{setError("");setItems(await fetchApi("/inventory/"));}catch(e){setError(e instanceof Error?e.message:"Could not load spare life data")}};useEffect(()=>{load()},[]);
  const shown=useMemo(()=>{const filtered=items.filter(i=>`${i.name} ${i.used_at||""} ${i.criticality||""}`.toLowerCase().includes(query.toLowerCase()));return [...filtered].sort((a,b)=>sort==="CRITICAL"?((rank[a.criticality||"UNASSESSED"]??9)-(rank[b.criticality||"UNASSESSED"]??9)||a.name.localeCompare(b.name,undefined,{numeric:true})):sort==="LOW_STOCK"?((a.availability_pct??999)-(b.availability_pct??999)||a.name.localeCompare(b.name,undefined,{numeric:true})):a.name.localeCompare(b.name,undefined,{numeric:true}));},[items,query,sort]);
  const summary=useMemo(()=>({critical:items.filter(i=>i.criticality==="CRITICAL"||i.criticality==="HIGH").length,short:items.filter(i=>(i.availability_pct??101)<100).length,total:items.length}),[items]);
  function openAdd(){setEditing(null);setForm(blank);setShowForm(true)}function openEdit(item:Item){setEditing(item);setForm({name:item.name,used_at:item.used_at||"",quantity:String(item.quantity),minimum_quantity:String(item.minimum_quantity||0),expected_life_hours:item.expected_life_hours?.toString()||"",observed_avg_life_hours:item.observed_avg_life_hours?.toString()||""});setShowForm(true)}
  async function saveSpare(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const payload={name:form.name.trim(),used_at:form.used_at.trim()||null,minimum_quantity:Math.floor(n(form.minimum_quantity)),expected_life_hours:optional(form.expected_life_hours),observed_avg_life_hours:optional(form.observed_avg_life_hours),location:"Store"};if(editing){await fetchApi(`/inventory/${editing.id}`,{method:"PATCH",body:JSON.stringify(payload)});const newQty=Math.floor(n(form.quantity));if(newQty!==editing.quantity){const operator=window.prompt("Updated by")?.trim();if(!operator)throw new Error("Quantity update cancelled because 'Updated by' was not entered.");await fetchApi(`/inventory/${editing.id}/set-quantity`,{method:"POST",body:JSON.stringify({quantity:newQty,operator,reason:"Spare register update"})});}}else{await fetchApi("/inventory/",{method:"POST",body:JSON.stringify({...payload,quantity:Math.floor(n(form.quantity)),remarks:null,reliability_pct:null,availability_pct:null,criticality:"UNASSESSED"})});}setShowForm(false);setEditing(null);setForm(blank);await load();}catch(e){setError(e instanceof Error?e.message:"Could not save spare")}finally{setSaving(false)}}
  async function quickQty(item:Item){const raw=window.prompt(`Store quantity for ${item.name}`,String(item.quantity));if(raw===null)return;const qty=Math.floor(Number(raw));if(!Number.isFinite(qty)||qty<0)return;const operator=window.prompt("Updated by")?.trim();if(!operator)return;try{await fetchApi(`/inventory/${item.id}/set-quantity`,{method:"POST",body:JSON.stringify({quantity:qty,operator,reason:"Store quantity update"})});await load();}catch(e){setError(e instanceof Error?e.message:"Could not update quantity")}}
  async function archive(item:Item){if(!window.confirm(`Remove ${item.name} from active spare list?`))return;try{await fetchApi(`/inventory/${item.id}`,{method:"DELETE"});await load();}catch(e){setError(e instanceof Error?e.message:"Could not remove spare")}}
  return <div className="dsr-page"><Header title="Spare Life"/><main className="dsr-main"><div className="full-bleed space-y-3">
    <div className="dsr-section-head"><div><div className="dsr-kicker">Store + reliability</div><h1 className="dsr-title">Spare Life</h1><p className="dsr-subtitle">Enter source values only. Availability, life performance and planning criticality are calculated.</p></div><button onClick={openAdd} className="dsr-btn-primary">+ Add Spare</button></div>
    <div className="grid grid-cols-3 gap-2"><div className="dsr-stat"><div className="dsr-stat-label">Active spares</div><div className="dsr-stat-value">{summary.total}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Below coverage</div><div className="dsr-stat-value text-amber-300">{summary.short}</div></div><div className="dsr-stat"><div className="dsr-stat-label">High / Critical</div><div className="dsr-stat-value text-red-300">{summary.critical}</div></div></div>
    <div className="mechanical-panel p-3 flex flex-col md:flex-row gap-2 md:items-center md:justify-between"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search spare or used at" className="input-class md:max-w-md"/><select value={sort} onChange={e=>setSort(e.target.value as any)} className="input-class md:w-auto"><option value="AZ">A → Z</option><option value="CRITICAL">Critical first</option><option value="LOW_STOCK">Lowest availability</option></select></div>
    {showForm&&<form onSubmit={saveSpare} className="mechanical-panel p-4"><div className="flex items-center justify-between gap-3 border-b border-slate-800 pb-3"><div><div className="dsr-kicker">{editing?"Edit spare":"New spare"}</div><div className="font-black text-white">{editing?editing.name:"Add Spare"}</div></div><button type="button" onClick={()=>setShowForm(false)} className="dsr-btn">Close</button></div><div className="mt-4 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-6 gap-3"><Field label="Spare name"><input className="input-class" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="Used at"><input className="input-class" value={form.used_at} onChange={e=>setForm({...form,used_at:e.target.value})}/></Field><Field label="Store Qty"><input className="input-class" type="number" min="0" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="Required Qty"><input className="input-class" type="number" min="0" value={form.minimum_quantity} onChange={e=>setForm({...form,minimum_quantity:e.target.value})}/></Field><Field label="Expected Life h"><input className="input-class" type="number" min="0" value={form.expected_life_hours} onChange={e=>setForm({...form,expected_life_hours:e.target.value})}/></Field><Field label="Observed Avg h"><input className="input-class" type="number" min="0" value={form.observed_avg_life_hours} onChange={e=>setForm({...form,observed_avg_life_hours:e.target.value})}/></Field></div><div className="mt-3 flex justify-end"><button disabled={saving} className="dsr-btn-primary min-w-[120px]">{saving?"Saving...":"Save"}</button></div></form>}
    {error&&<div className="rounded-lg border border-red-900 bg-red-950/25 p-3 text-xs text-red-300">{error}</div>}
    <div className="dsr-table-wrap"><table className="dsr-table min-w-[980px]"><thead><tr><th className="dsr-th">Spare</th><th className="dsr-th">Used At</th><th className="dsr-th text-center">Store</th><th className="dsr-th text-center">Required</th><th className="dsr-th text-center">Availability</th><th className="dsr-th text-center">Expected Life</th><th className="dsr-th text-center">Observed</th><th className="dsr-th text-center">Reliability</th><th className="dsr-th text-center">Criticality</th><th className="dsr-th text-center">Action</th></tr></thead><tbody>{shown.map(item=><tr key={item.id} className="hover:bg-slate-900/55"><td className="dsr-td font-black text-white">{item.name}</td><td className="dsr-td">{item.used_at||"—"}</td><td className="dsr-td text-center font-black text-white">{item.quantity}</td><td className="dsr-td text-center">{item.minimum_quantity||"—"}</td><td className="dsr-td text-center font-bold">{pct(item.availability_pct)}</td><td className="dsr-td text-center">{life(item.expected_life_hours)}</td><td className="dsr-td text-center">{life(item.observed_avg_life_hours)}</td><td className="dsr-td text-center font-bold">{pct(item.reliability_pct)}</td><td className="dsr-td text-center"><span className={`inline-flex rounded-md border px-2 py-1 text-[9px] font-black ${badge(item.criticality)}`}>{item.criticality||"UNASSESSED"}</span></td><td className="dsr-td"><div className="flex justify-center gap-1"><button onClick={()=>quickQty(item)} className="dsr-btn !min-h-0 !px-2 !py-1">Qty</button><button onClick={()=>openEdit(item)} className="dsr-btn !min-h-0 !px-2 !py-1">Edit</button><button onClick={()=>archive(item)} className="dsr-btn !min-h-0 !px-2 !py-1 text-red-300">Remove</button></div></td></tr>)}{shown.length===0&&<tr><td colSpan={10} className="dsr-empty">No matching spares.</td></tr>}</tbody></table></div>
  </div></main></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="metric-label">{label}</span><div className="mt-1.5">{children}</div></label>}
