"""Initial schema setup

Revision ID: 967dbde99978
Revises: 
Create Date: 2026-08-15 00:15:18.422096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967dbde99978'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_lines_id'), 'lines', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_table('entry_guide_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('current_location', sa.Enum('READY_AREA', 'WRM_LINE', 'WIP', name='locationenum'), nullable=False),
    sa.Column('current_status', sa.Enum('READY', 'INSTALLED', 'MAINTENANCE', name='statusenum'), nullable=False),
    sa.Column('current_position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_guide_assets_code'), 'entry_guide_assets', ['code'], unique=True)
    op.create_index(op.f('ix_entry_guide_assets_id'), 'entry_guide_assets', ['id'], unique=False)
    op.create_table('stand_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('current_location', sa.Enum('READY_AREA', 'WRM_LINE', 'WIP', name='locationenum'), nullable=False),
    sa.Column('current_status', sa.Enum('READY', 'INSTALLED', 'MAINTENANCE', name='statusenum'), nullable=False),
    sa.Column('current_position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stand_assets_code'), 'stand_assets', ['code'], unique=True)
    op.create_index(op.f('ix_stand_assets_id'), 'stand_assets', ['id'], unique=False)
    op.create_table('entry_guide_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guide_id'], ['entry_guide_assets.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_guide_installations_id'), 'entry_guide_installations', ['id'], unique=False)
    op.create_table('stand_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stand_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stand_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stand_installations_id'), 'stand_installations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stand_installations_id'), table_name='stand_installations')
    op.drop_table('stand_installations')
    op.drop_index(op.f('ix_entry_guide_installations_id'), table_name='entry_guide_installations')
    op.drop_table('entry_guide_installations')
    op.drop_index(op.f('ix_stand_assets_id'), table_name='stand_assets')
    op.drop_index(op.f('ix_stand_assets_code'), table_name='stand_assets')
    op.drop_table('stand_assets')
    op.drop_index(op.f('ix_entry_guide_assets_id'), table_name='entry_guide_assets')
    op.drop_index(op.f('ix_entry_guide_assets_code'), table_name='entry_guide_assets')
    op.drop_table('entry_guide_assets')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lines_id'), table_name='lines')
    op.drop_table('lines')
    # ### end Alembic commands ###