"use client";

import { useEffect, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Kind="STAND_TRACKING"|"SPARE_USAGE"|"PROCESS_PARAMETERS";
type Preview={kind:string;filename:string;records:number;with_reasons?:number;spares?:number;lines?:string[];mapping?:Record<string,string>;date_from?:string;date_to?:string;note?:string};
type CardState={file:File|null;preview:Preview|null;loading:boolean;message:string;error:string};
const DATASETS:{kind:Kind;title:string;hint:string;example:string;tone:string}[]=[
  {kind:"STAND_TRACKING",title:"Stand Tracking History",hint:"Running snapshots become inferred stand campaigns.",example:"Stand Tracking 2025.xlsx",tone:"border-blue-900/60 bg-blue-950/10"},
  {kind:"SPARE_USAGE",title:"Spare Utilization History",hint:"Daily spare consumption remains a separate historical dataset.",example:"Spare Utilized.xlsx",tone:"border-emerald-900/60 bg-emerald-950/10"},
  {kind:"PROCESS_PARAMETERS",title:"WRM Process Parameters",hint:"Process conditions stay separate for engineering correlation.",example:"WRM Parameter Report JUNE 2026.xlsx",tone:"border-violet-900/60 bg-violet-950/10"},
];
const blank=():CardState=>({file:null,preview:null,loading:false,message:"",error:""});
export default function HistoricalImportPage(){
  const [summary,setSummary]=useState<any>(null);const [states,setStates]=useState<Record<Kind,CardState>>({STAND_TRACKING:blank(),SPARE_USAGE:blank(),PROCESS_PARAMETERS:blank()});
  const loadSummary=async()=>{try{setSummary(await fetchApi("/historical/summary"));}catch{}};useEffect(()=>{loadSummary()},[]);
  const patch=(kind:Kind,part:Partial<CardState>)=>setStates(s=>({...s,[kind]:{...s[kind],...part}}));
  async function preview(kind:Kind){const s=states[kind];if(!s.file)return;patch(kind,{loading:true,error:"",message:"",preview:null});try{const fd=new FormData();fd.append("file",s.file);fd.append("expected_kind",kind);const r=await fetchApi("/historical/preview",{method:"POST",body:fd});patch(kind,{preview:r});}catch(e:any){patch(kind,{error:e.message});}finally{patch(kind,{loading:false});}}
  async function importData(kind:Kind){const s=states[kind];if(!s.file||!s.preview)return;if(!window.confirm(`Import ${s.preview.records} reviewed records?`))return;patch(kind,{loading:true,error:""});try{const fd=new FormData();fd.append("file",s.file);fd.append("expected_kind",kind);const r=await fetchApi("/historical/import",{method:"POST",body:fd});patch(kind,{message:`Imported ${r.inserted}; skipped ${r.skipped} existing records.`});await loadSummary();}catch(e:any){patch(kind,{error:e.message});}finally{patch(kind,{loading:false});}}
  return <div className="dsr-page"><Header title="Historical Data"/><main className="dsr-main"><div className="full-bleed space-y-4">
    <div className="dsr-section-head"><div><div className="dsr-kicker">Reliability history</div><h1 className="dsr-title">Historical Data</h1><p className="dsr-subtitle">Import each source separately. Live DSR records remain the source of truth.</p></div></div>
    {summary&&<section className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="dsr-stat border-blue-900/60 bg-blue-950/10"><div className="dsr-stat-label">Campaigns</div><div className="dsr-stat-value text-blue-300">{summary.campaigns}</div><div className="helper-text">{summary.campaign_files||0} file(s)</div></div><div className="dsr-stat border-emerald-900/60 bg-emerald-950/10"><div className="dsr-stat-label">Spare usage</div><div className="dsr-stat-value text-emerald-300">{summary.spare_usage_rows}</div><div className="helper-text">{summary.spare_files||0} file(s)</div></div><div className="dsr-stat border-violet-900/60 bg-violet-950/10"><div className="dsr-stat-label">Process observations</div><div className="dsr-stat-value text-violet-300">{summary.process_observations}</div><div className="helper-text">{summary.process_files||0} file(s)</div></div></section>}
    <section className="grid grid-cols-1 xl:grid-cols-3 gap-4">{DATASETS.map(ds=>{const s=states[ds.kind];return <div key={ds.kind} className={`rounded-xl border p-4 space-y-3 ${ds.tone}`}><div><div className="dsr-kicker">Separate dataset</div><h2 className="mt-1 font-bold text-white">{ds.title}</h2><p className="mt-1 text-xs text-slate-400 min-h-9">{ds.hint}</p></div><div className="helper-text">Example: {ds.example}</div><input type="file" accept=".xlsx" onChange={e=>patch(ds.kind,{file:e.target.files?.[0]||null,preview:null,message:"",error:""})} className="w-full text-xs text-slate-300 file:mr-2 file:rounded-md file:border-0 file:bg-slate-700 file:px-3 file:py-2 file:text-slate-100"/><div className="flex gap-2"><button disabled={!s.file||s.loading} onClick={()=>preview(ds.kind)} className="dsr-btn-primary disabled:opacity-40">{s.loading?"Working...":"Preview"}</button><button disabled={!s.preview||s.loading} onClick={()=>importData(ds.kind)} className="dsr-btn !text-emerald-300 disabled:opacity-40">Import reviewed</button></div>{s.preview&&<div className="rounded-lg border border-slate-700/70 bg-slate-950/35 p-3 text-xs space-y-1"><div className="font-bold text-white break-all">{s.preview.filename}</div><div>Detected: {s.preview.kind.replaceAll("_"," ")}</div><div>Records: <b>{s.preview.records}</b></div>{s.preview.with_reasons!=null&&<div>Changes with remarks: {s.preview.with_reasons}</div>}{s.preview.spares!=null&&<div>Unique spares: {s.preview.spares}</div>}{s.preview.date_from&&<div>Period: {s.preview.date_from} → {s.preview.date_to}</div>}{s.preview.mapping&&<div className="text-violet-300">WRM3 → W1 · WRM4 → W2 · WRM5 → W3</div>}{s.preview.note&&<div className="text-amber-300">{s.preview.note}</div>}</div>}{s.message&&<div className="text-xs text-emerald-300">✓ {s.message}</div>}{s.error&&<div className="text-xs text-red-300">{s.error}</div>}</div>})}</section>
    <section className="rounded-xl border border-amber-900/60 bg-amber-950/10 p-4 text-xs text-slate-400"><b className="text-amber-200">Source hierarchy:</b> live DSR campaigns are exact. Historical stand sheets are inferred; spare history and process parameters remain independent supporting evidence.</section>
  </div></main></div>;
}
