"use client";

import { useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Summary={data:{campaigns:number;spare_usage_rows:number;process_observations:number};line_stats:any[];weak_positions:any[];cause_pareto:any[];repeat_low_life:any[];top_spares:any[];process_screen:any[];method_note:string};
type Chat={role:"user"|"assistant";text:string};
const fmt=(v:any,suffix="")=>v===null||v===undefined?"—":`${v}${suffix}`;const clean=(s:string)=>(s||"").replaceAll("_"," ");
export default function IntelligencePage(){
  const [data,setData]=useState<Summary|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [question,setQuestion]=useState("");const [asking,setAsking]=useState(false);const [chat,setChat]=useState<Chat[]>([{role:"assistant",text:"Ask about a line, position, weak stand life, common causes or spare consumption. Example: Investigate W1 P8."}]);
  const load=async()=>{setLoading(true);setError("");try{setData(await fetchApi("/intelligence/summary"));}catch(e:any){setError(e.message||"Could not load intelligence");}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const attention=useMemo(()=>data?[...data.weak_positions].filter((x:any)=>x.vs_position_baseline_pct<0).slice(0,5):[],[data]);
  async function ask(text?:string){const q=(text??question).trim();if(!q||asking)return;setQuestion("");setChat(c=>[...c,{role:"user",text:q}]);setAsking(true);try{const up=q.toUpperCase();const line=up.match(/\bW([123])\b/)?.[0];const posMatch=up.match(/\bP(?:OSITION\s*)?(10|[1-9])\b/)||up.match(/\bPOSITION\s*(10|[1-9])\b/);let answer="";if(line&&posMatch){const pos=Number(posMatch[1]);const r=await fetchApi(`/investigation/position?line=${line}&position=${pos}`);if(!r.campaigns){answer=`${line} P${pos}: no measurable historical campaigns yet. Keep collecting stand-change history before drawing a life conclusion.`;}else{const cause=r.causes?.[0];const weak=r.early_campaigns?`${r.early_campaigns} early-life campaign${r.early_campaigns===1?"":"s"}`:"no early-life campaigns";answer=`${line} P${pos}: ${r.campaigns} campaigns, average life ${fmt(r.avg_days," d")}, median ${fmt(r.median_days," d")}, ${weak}. ${cause?`Most common recorded cause: ${clean(cause.cause)} (${cause.count}). `:""}${r.stand_codes?.[0]?`Lowest-life repeated stand: ${r.stand_codes[0].stand} (${fmt(r.stand_codes[0].avg_days," d")} avg). `:""}Treat process/spare links as screening evidence, not confirmed root cause.`;}}else if(/WEAK|LOW LIFE|WORST|ATTENTION/.test(up)&&data){const rows=data.weak_positions.filter((x:any)=>x.vs_position_baseline_pct<0).slice(0,5);answer=rows.length?`Positions needing attention: ${rows.map((x:any)=>`${x.line} P${x.position} (${x.vs_position_baseline_pct}% vs baseline)`).join(", ")}. Ask me to investigate one.`:"No below-baseline positions are available yet.";}else if(/CAUSE|FAIL|WHY/.test(up)&&data){answer=data.cause_pareto.length?`Most frequent recorded causes: ${data.cause_pareto.slice(0,5).map((x:any)=>`${clean(x.cause)} (${x.count})`).join(", ")}. These are historical frequencies, not proof of the current root cause.`:"No usable removal-cause history is available yet.";}else if(/SPARE|CONSUM/.test(up)&&data){answer=data.top_spares.length?`Highest historical spare usage: ${data.top_spares.slice(0,5).map((x:any)=>`${x.spare} (${x.quantity})`).join(", ")}. Use Spare Life for current coverage.`:"No historical spare-usage records are available yet.";}else{answer="Try: Investigate W1 P8 · Which positions are weak? · What are common failure causes? · Show top spare consumption.";}setChat(c=>[...c,{role:"assistant",text:answer}]);}catch(e:any){setChat(c=>[...c,{role:"assistant",text:e.message||"Could not investigate that request."}]);}finally{setAsking(false)}}
  return <div className="dsr-page"><Header title="Intelligence"/><main className="dsr-main"><div className="full-bleed space-y-3"><div className="dsr-section-head"><div><div className="dsr-kicker">Reliability assistant</div><h1 className="dsr-title">Stand Intelligence</h1><p className="dsr-subtitle">Verified plant calculations first. AI-style interpretation second. Engineering decision always stays with the user.</p></div><button onClick={load} className="dsr-btn">Refresh</button></div>
  {loading&&<div className="dsr-empty">Loading reliability history...</div>}{error&&<div className="rounded-lg border border-red-900 bg-red-950/25 p-3 text-xs text-red-300">{error}</div>}
  <div className="grid gap-3 xl:grid-cols-[minmax(0,1.3fr)_minmax(300px,.7fr)]"><section className="mechanical-panel overflow-hidden min-h-[520px] flex flex-col"><div className="px-4 py-3 border-b border-slate-800 flex items-center justify-between"><div><div className="dsr-kicker">Ask</div><div className="text-sm font-black text-white">Stand Assistant</div></div><span className="dsr-chip">Evidence first</span></div><div className="flex-1 p-3 md:p-4 space-y-3 overflow-auto max-h-[520px]">{chat.map((m,i)=><div key={i} className={`max-w-[88%] rounded-xl border p-3 text-sm leading-relaxed ${m.role==="user"?"ml-auto border-cyan-800/60 bg-cyan-950/15 text-cyan-100":"mr-auto border-slate-800 bg-[#0a0f15] text-slate-200"}`}>{m.text}</div>)}{asking&&<div className="text-[11px] text-slate-500">Investigating plant history…</div>}</div><div className="border-t border-slate-800 p-3 bg-[#0a0f15]/70"><div className="flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask();}} placeholder="Ask: Investigate W2 P9" className="input-class flex-1"/><button onClick={()=>ask()} disabled={asking} className="dsr-btn-primary min-w-[72px]">Ask</button></div><div className="flex gap-1.5 mt-2 overflow-x-auto pb-1">{["Which positions are weak?","Common failure causes?","Top spare consumption"].map(x=><button key={x} onClick={()=>ask(x)} className="dsr-chip whitespace-nowrap hover:text-white">{x}</button>)}</div></div></section>
  <aside className="space-y-3"><section className="mechanical-panel overflow-hidden"><div className="px-4 py-3 border-b border-slate-800"><div className="dsr-kicker">Priority</div><div className="text-sm font-black text-white">Needs Attention</div></div><div className="p-2 space-y-2">{attention.length?attention.map((x:any)=><button key={`${x.line}-${x.position}`} onClick={()=>ask(`Investigate ${x.line} P${x.position}`)} className="w-full rounded-lg border border-slate-800 bg-[#0a0f15] p-3 text-left hover:border-cyan-800/70"><div className="flex items-center justify-between"><span className="font-black text-white">{x.line} · P{x.position}</span><span className="text-xs font-black text-amber-300">{x.vs_position_baseline_pct}%</span></div><div className="mt-1 text-[10px] text-slate-500">Avg {fmt(x.avg_days," d")} · {x.campaigns} campaigns</div></button>):<div className="dsr-empty">No below-baseline positions.</div>}</div></section>{data&&<section className="mechanical-panel p-3"><div className="dsr-kicker mb-2">Line baseline</div><div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-1">{data.line_stats.map((x:any)=><div key={x.line} className="rounded-lg border border-slate-800 bg-[#0a0f15] p-3 flex items-center justify-between"><div><div className="text-sm font-black text-cyan-300">{x.line}</div><div className="text-[9px] text-slate-500">{x.campaigns} campaigns</div></div><div className="text-right"><div className="metric-label">Avg life</div><div className="font-black text-white">{fmt(x.avg_days," d")}</div></div></div>)}</div></section>}</aside></div>
  <div className="text-[9px] text-slate-600">Detailed investigation is invoked only when needed; it no longer appears as a separate workflow.</div>
  </div></main></div>
}
